# Generated by Django 5.0.6 on 2024-06-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='score',
        ),
    ]
