# Generated by Django 5.0 on 2024-05-31 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
