# Generated by Django 5.0.6 on 2024-06-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_accountant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
