# Generated by Django 5.0.6 on 2024-06-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_is_accountant_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('поставщик', 'Поставщик'), ('клиент', 'Клиент'), ('админ', 'Админ'), ('продавец', 'Продавец'), ('бухгалтер', 'Бухгалтер')], default=('поставщик', 'Поставщик'), max_length=50),
        ),
    ]
